site_name: My Docs

# CSS
extra_css:
  - stylesheets/extra.css

# Theme
theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Plugins
plugins:
    - search
    # - pdf-export:
    #     verbose: true
    #     combined: true
    #     media_type: print
    #     enabled_if_env: ENABLE_PDF_EXPORT

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Topic 1:
    - Topic 1.1:
      - Topic 1.1.1: Topic1/Topic1.1/Topic1.1.1.md
      - Topic 1.1.2: Topic1/Topic1.1/Topic1.1.2.md
      - Topic 1.1.3: Topic1/Topic1.1/Topic1.1.3.md
    - Topic 1.2:
      - Topic 1.2.1: Topic1/Topic1.2/Topic1.2.1.md
      - Topic 1.2.2: Topic1/Topic1.2/Topic1.2.2.md
      - Topic 1.2.3: Topic1/Topic1.2/Topic1.2.3.md
    - Topic 1.3:
      - Topic 1.3.1: Topic1/Topic1.3/Topic1.3.1.md
      - Topic 1.3.2: Topic1/Topic1.3/Topic1.3.2.md
      - Topic 1.3.3: Topic1/Topic1.3/Topic1.3.3.md
  - Topic 2:
    - Topic 2.1:
      - Topic 2.1.1: Topic2/Topic2.1/Topic2.1.1.md
      - Topic 2.1.2: Topic2/Topic2.1/Topic2.1.2.md
      - Topic 2.1.3: Topic2/Topic2.1/Topic2.1.3.md
    - Topic 2.2:
      - Topic 2.2.1: Topic2/Topic2.2/Topic2.2.1.md
      - Topic 2.2.2: Topic2/Topic2.2/Topic2.2.2.md
      - Topic 2.2.3: Topic2/Topic2.2/Topic2.2.3.md
    - Topic 2.3:
      - Topic 2.3.1: Topic2/Topic2.3/Topic2.3.1.md
      - Topic 2.3.2: Topic2/Topic2.3/Topic2.3.2.md
      - Topic 2.3.3: Topic2/Topic2.3/Topic2.3.3.md
  - Topic 3:
    - Topic 3.1:
      - Topic 3.1.1: Topic3/Topic3.1/Topic3.1.1.md
      - Topic 3.1.2: Topic3/Topic3.1/Topic3.1.2.md
      - Topic 3.1.3: Topic3/Topic3.1/Topic3.1.3.md
    - Topic 3.2:
      - Topic 3.2.1: Topic3/Topic3.2/Topic3.2.1.md
      - Topic 3.2.2: Topic3/Topic3.2/Topic3.2.2.md
      - Topic 3.2.3: Topic3/Topic3.2/Topic3.2.3.md
    - Topic 3.3:
      - Topic 3.3.1: Topic3/Topic3.3/Topic3.3.1.md
      - Topic 3.3.2: Topic3/Topic3.3/Topic3.3.2.md
      - Topic 3.3.3: Topic3/Topic3.3/Topic3.3.3.md
