name: ci 

on:
  push:
    branches: 
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install ghp-import
      - name: Checkout 
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
      - uses: addnab/docker-run-action@v3
        with:
          registry: registry.hub.docker.com
          image: dimayasenko/mkdocs-material:latest
          options: --user root -v ${{ github.workspace }}:/docs:rw -e ABC=123
          run: mkdocs build
#       - run: ls
#       - run: ghp-import -o site
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages 
          folder: site
              
